// Code Generated by Sidekick is for learning and experimentation purposes only.
using Yarp.ReverseProxy;

var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddReverseProxy()
    .LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"));

var app = builder.Build();
app.MapGet("/health", () => Results.Ok("API Gateway is running"));

app.MapReverseProxy();

app.Run();
